<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.presenter.order_link_presenter' shared service.

return $this->services['prestashop.adapter.presenter.order_link_presenter'] = new \PrestaShop\PrestaShop\Adapter\Presenter\Order\OrderLinkPresenter(${($_ = isset($this->services['prestashop.router']) ? $this->services['prestashop.router'] : $this->load('getPrestashop_RouterService.php')) && false ?: '_'});
